# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# Default entry index (0-based). 0 = first entry.
default_entry: 0

# Menu entry
/nimos
    # Use the Limine boot protocol.
    protocol: limine

    # Path to your kernel. boot():/ is the partition with limine.conf.
    path: boot():/kernel.elf
